### PR TITLE
use withDatasourceCheck in FeaturedEvent and Section

### LINKED ISSUE #182: FeaturedEvent and Section: the component is rendered with no data in FE rendering host
If the Data Source of the FeaturedEvent and Section is empty the component is displayed in FE. The `withDatasourceCheck` should be used in those two components. A PR is created for this issue #183 

image

image

### PR DESCRIPTION
**Pull request by gkLeo**
Fixes #182

### CODE REVIEW

**Comment by adoprog** [comment]
@gkLeo Build fails - please try to run it locally with 'npm run build'

**Comment by gkLeo** [comment]
@adoprog issue is resolved.

**Comment by adoprog** [comment]
I've noticed that Section no longer renders in Storybook after the changes. Please compare Vercel preview to the main Storybook.

**Comment by gkLeo** [comment]
@adoprog  It works now

image

**Pull request merged**
